clusterName: ""
projectName: ""
nodeRole: ""
capacityType:
  - on-demand
cpuLimit: "100"
metadataOptions:
  httpEndpoint: enabled
  httpProtocolIPv6: disabled
  httpPutResponseHopLimit: 1
  httpTokens: required
